version: "3"
services:
  app:
    build: .
    image: alsaaudio
    user: 1000:1000
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    

